# Variables
# API_URL -> http://localhost:3000
# POSTMARK_API_KEY -> POSTMARK_API_KEY
# FROM_SENDER -> POSTMARK_API_KEY


version: "3"
services:
  db:
    container_name: mongo
    image: mongo
    restart: on-failure
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: stg-api
    depends_on:
      - 'db'
    restart: always
    build: ../FHNW-SQL-Training-Game-API
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stg-api
      - JWT_SECRET=FHNW_2021
      - FROM_SENDER=${FROM_SENDER}
      - POSTMARK_API_KEY=${POSTMARK_API_KEY}
      - PORT=3001
      - IO_URL=${IO_URL} 
    ports:
      - "3001:3001"
  frontend:
    container_name: stg-frontend
    depends_on:
      - 'api'
    restart: always
    build:
      context: .
      args:
        API_URL: ${API_URL}
        API_URL_PUBLIC: ${API_URL_PUBLIC}
    ports:
      - "80:80"
      - "3000:3000"
  model:
    container_name: model-python
    restart: always
    build:
      context: .
      dockerfile: Model-implementation/Dockerfile
      args:
        API_URL: ${API_URL}
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stg-api
    ports:
      - "5001:5001"